
export const DATA_ARTICLE_REQUEST = 'DATA_ARTICLE_REQUEST'
export const DATA_ARTICLE = 'DATA_ARTICLE'
export const DATA_ARTICLE_FAILED = 'DATA_ARTICLE_FAILED'
export const DATA_ARTICLE_DETAIL = 'DATA_ARTICLE_DETAIL'
export const DATA_ARTICLE_SUCCES = 'DATA_ARTICLE_SUCCES'